### ISSUE TITLE
[FEATURE] Adding tests

### ISSUE THREAD

**Issue by qcoumes** [leonhard-s/auraxium#2]
Since the Census API might change at any moment (and break at any moment...), it could be very useful to have tests to ensure everything is working. Either to fix things on our side, or to warn the devs that they broke something.

**Comment by qcoumes** [comment]
I'm currently working on a higher level object approach to the PS2 API (like your old `auraxiumm.object_models.ps2`), so I'd like to add tests on these new classes.

I usually go with `tox`, and pair it with [Travis-CI](https://travis-ci.com/) to run my tests weekly, but it's optional.

Are you fine with `tox` or do you prefer an alternative? Do you want me to set up a *Travis* configuration?

**Comment by LordFlashmeow** [comment]
I'm not the owner, but I am personally a fan of unittests for the base level test running, as it's very legible for people new to the codebase

**Comment by leonhard-s** [comment]
> I'm currently working on a higher level object approach to the PS2 API (like your old auraxiumm.object_models.ps2), so I'd like to add tests on these new classes.

@qcoumes That's great to hear - I have been meaning to expand the object model API, ideally adding a lot more async and caching.

> I'm not the owner, but I am personally a fan of unittests for the base level test running, as it's very legible for people new to the codebase

But I am - how serendipitous!

Thank both of you for the input. I have been meaning to add unittests myself, but I never got around to it.
As you probably noticed, I have not been looking after this repo for a while - I shall change that now that there is interest. 😄

I will give the repo a quick once-over during the weekend, probably going to add unit tests for the core functionality next week.

**Comment by leonhard-s** [comment]
A few closing remarks on this issue since a lot of it has been touched by recent commits:

### Detecting breaking API changes

The object representations for PS2 data types are hard-coded to expect the fields currently available. This will raise a `BadPayloadError` to show that the object model is no longer compatible with the API. There is currently no warning system in place to warn us of new fields being added to a collection as this would often provide false positives for queries containing joins.

### Automated tests

I added some `unittest` test cases for `auraxium.census` and `auraxium.cache`, the only modules I consider somewhat finished at this stage. They are also automatically run for any commits through GitHub actions.

I will be adding more tests as I gain confidence in the individual submodules, especially a script to validate the field lists for all of PS2's API collections would be extremely useful.

### API outages

The API currently provides helpful errors when the API reports as undergoing maintenance or being unavailable, but a lot of maintenance states involve redirects to `*.sony.com` URLs, which result in a lower-level HTTP error due to these pages no longer existing.

This is an open problem that will be tracked in a new issue (#14).
