### ISSUE TITLE
ClientResponseError: 400, message='Bad Request' when querying census API

### ISSUE THREAD

**Issue by yakMM** [leonhard-s/auraxium#64]
Hello, I'm recently getting an error when querying the census API with auraxium.

I don't know if the problem is coming from an API change on Daybreak side or a recent change in the auraxium module.

The problem is fixed if I cast the url to str (using `str(url)` instead of `url`) here: https://github.com/leonhard-s/auraxium/blob/8fd4fa9eaa77ecd3b4cba571c285a4776aeaa119/auraxium/_rest.py#L484

Does the problem come from using yarl.URL object directly?

**Comment by leonhard-s** [comment]
Hi, thank you for the report. I have been observing similar issues in the CI runs for https://github.com/leonhard-s/ps2-api-backup but was unable to reproduce it locally.

I will do some digging to see what caused this; there have been no changes to Auraxium lately. Either a new version of yarl changed a behaviour, or it was an API change.

**Comment by leonhard-s** [comment]
The error appears to have been an upstream issue related to a regression in `yarl==1.9.1` or one of its dependencies. Version 1.9.2 of `yarl` no longer breaks requests.

I do not immediately see a connection to the only regression they mention in the release notes (https://github.com/aio-libs/yarl/issues/854), but I have not had time to investigate it in detail. Especially the explicit cast to `str` fixing the issue is quite interesting.

@yakMM please let me know if the issue is fixed for you after updating to `yarl` 1.9.2.

**Comment by yakMM** [comment]
The issue is indeed resolved with `yarl ` 1.9.2, thanks.

Didn't really look in details, plus I don't really know about yarl, but the issue you are linking resembles very much the weird behavior I was experimenting.
